# Generated by Django 3.0.8 on 2020-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('CodigoEmpleado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=75)),
                ('Apellido', models.CharField(max_length=75)),
                ('Telefono', models.CharField(max_length=12)),
                ('DPI', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=75)),
            ],
        ),
    ]
