# Generated by Django 3.0.8 on 2020-08-15 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('CodigoProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProyecto', models.CharField(max_length=75)),
                ('empleado_CodigoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.Empleado')),
            ],
        ),
    ]
