# Generated by Django 3.0.8 on 2020-08-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosPro',
            fields=[
                ('CodigoRecursos', models.AutoField(primary_key=True, serialize=False)),
                ('Personal', models.CharField(max_length=20)),
                ('Presupuesto', models.CharField(max_length=20)),
                ('Maquinas', models.CharField(max_length=75)),
                ('ContracionServicios', models.CharField(max_length=75)),
                ('proyecto_CodigoProyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyect.proyect')),
            ],
        ),
    ]
