# Generated by Django 3.0.8 on 2020-08-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleado', '0001_initial'),
        ('TipoProyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('CodigoProyecto', models.AutoField(primary_key=True, serialize=False)),
                ('NombreProyecto', models.CharField(max_length=75)),
                ('Personal', models.CharField(max_length=12)),
                ('Presupuesto', models.CharField(max_length=20)),
                ('Maquinas', models.CharField(max_length=75)),
                ('ContracionServicios', models.CharField(max_length=75)),
                ('FechaInicio', models.DateField()),
                ('FechaEntrega', models.DateField()),
                ('empleado_CodigoEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleado.Empleado')),
                ('tipopro_CodigoTipoPro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoProyecto.TipoProyecto')),
            ],
        ),
    ]
